"""Public rejection codes for the receivable and P02 HTTP boundaries.

Internal exceptions are never API messages. Preserve the existing business-code
vocabulary through owned literals; unknown messages, extra arguments and string
subclasses receive a fixed public rejection. Do not normalize or stringify them.
"""

_PUBLIC_CODES = (
    'actor_owner_and_reason_required',
    'aggregate_identity_not_postable',
    'canonical_provider_id_required',
    'capture_amount_conflict',
    'capture_currency_conflict',
    'capture_date_conflict',
    'capture_evidence_incomplete',
    'capture_not_confirmed',
    'capture_total_conflict',
    'cod_collection_order_amount_conflict',
    'cod_order_already_recognized_elsewhere',
    'cod_refund_requires_review',
    'cod_sale_existing_journal_requires_review',
    'courier_delivery_evidence_required',
    'courier_identity_or_waybill_missing',
    'courier_waybill_not_unique',
    'daily_movement_already_consumed',
    'daily_movement_bank_missing',
    'daily_movement_concurrent_consumption',
    'daily_movement_date_invalid',
    'daily_movement_not_available',
    'daily_movement_not_found',
    'event_date_conflict',
    'existing_journal_requires_review',
    'explicit_value_required',
    'fulfilment_not_proven',
    'future_source_event',
    'incoming_payment_conflict',
    'incoming_refund_conflict',
    'invalid_amount',
    'invalid_date',
    'invalid_decimal',
    'invalid_event_date',
    'invalid_policy_revision',
    'order_evidence_conflict',
    'order_evidence_missing',
    'order_creation_timestamp_required',
    'order_creation_timestamp_invalid',
    'order_has_prior_shipping_fee_event',
    'order_identity_mismatch',
    'order_is_not_cod',
    'order_payment_method_mismatch',
    'order_principal_conflict',
    'original_currency_conflict',
    'original_order_principal_conflict',
    'original_recognition_required',
    'original_sale_amount_conflict',
    'original_split_conflict',
    'owner_mismatch',
    'payment_evidence_missing',
    'policy_changed_refresh_required',
    'policy_history_limit',
    'positive_gross_required',
    'pre_cutover_invoice_requires_reclassification',
    'pre_cutover_recognition',
    'pre_cutover_order',
    'preview_changed_review_again',
    'previous_post_result_requires_recovery',
    'previous_recognition_source_conflict',
    'provider_evidence_unverified',
    'provider_mismatch',
    'provider_movement_cannot_be_shipping_settlement',
    'provider_suggestion_must_be_resolved_first',
    'rate_out_of_range',
    'recognition_cutoff_not_configured',
    'refund_currency_conflict',
    'refund_date_conflict',
    'refund_evidence_missing',
    'refund_exceeds_original',
    'refund_exceeds_sale',
    'refund_history_conflict',
    'refund_history_requires_recovery',
    'refund_not_confirmed',
    'refund_order_mismatch',
    'refund_owner_provider_mismatch',
    'refund_payment_mismatch',
    'refund_provenance_required',
    'refund_requires_daily_movement_approval',
    'sales_tax_not_configured_for_date',
    'sar_evidence_required',
    'shipping_accounting_date_invalid',
    'shipping_accounting_date_required',
    'shipping_accounting_timezone_required',
    'shipping_amount_invalid',
    'shipping_amount_must_be_positive',
    'shipping_counterparty_missing',
    'shipping_event_in_future',
    'shipping_event_requires_recovery',
    'shipping_event_source_conflict',
    'shipping_fee_payment_requires_outflow',
    'shipping_net_offset_required',
    'shipping_offset_not_allowed',
    'shipping_rate_ambiguous',
    'shipping_rate_not_configured',
    'shipping_rate_tax_treatment_unsupported',
    'shipping_settlement_amount_required',
    'shipping_settlement_requires_inflow',
    'source_payment_currency_conflict',
    'source_payment_identity_conflict',
    'source_provenance_required',
    'store_driver_cod_requires_cash_collection',
    'store_driver_collection_amount_conflict',
    'store_driver_collection_identity_missing',
    'store_driver_collection_missing',
    'store_driver_collection_requires_review',
    'store_driver_earning_missing',
    'store_driver_missing',
    'sub_cent_amount',
    'timezone_required',
    'unique_cod_order_evidence_required',
    'unique_source_order_required',
    'unique_order_creation_evidence_required',
    'unsupported_provider',
)


def public_accounting_error(exc: Exception) -> str:
    """Return a catalog-owned code, never text copied from an exception."""
    args = exc.args
    if len(args) == 1 and type(args[0]) is str:
        for public_code in _PUBLIC_CODES:
            if args[0] == public_code:
                return public_code
    return "accounting_request_rejected"
