"""Pre-Production evaluation corpus requested for Decision Intelligence V3.

The expected fields are deliberately broad invariants, not deterministic ROAS
rules.  A live OpenAI eval may choose among several reasonable diagnoses/actions
as long as it respects the root-cause and counterfactual constraints.
"""

SCENARIOS = [
    {
        "id": "today_bad_yesterday_excellent",
        "description": "اليوم ضعيف لكن أمس ممتاز والحجم الحالي متوسط فقط",
        "evidence": "Today deteriorated vs baseline; yesterday was excellent; no site/product alerts.",
        "must_not_actions": ["PAUSE_CAMPAIGN"],
        "acceptable_root_causes": ["NORMAL_VARIANCE", "INSUFFICIENT_DATA", "UNKNOWN"],
        "principle": "single-day deterioration must be challenged before pause",
    },
    {
        "id": "three_bad_days_historically_excellent",
        "description": "3 أيام ضعيفة لكن 30 يوم تاريخيًا ممتازة",
        "evidence": "Today, yesterday and day-2 are weak; 30d baseline historically strong.",
        "must_review": ["CREATIVE", "AUDIENCE", "PRODUCT", "SEASONALITY", "WEBSITE"],
        "principle": "persistent deviation needs diagnosis, history is context not immunity",
    },
    {
        "id": "weak_ctr",
        "description": "CTR ضعيف مع صفحة ومنتج سليمين",
        "evidence": "Impressions normal, CTR materially below own baseline, downstream sample sparse.",
        "acceptable_root_causes": ["CREATIVE", "AUDIENCE", "OFFER"],
        "principle": "diagnose click intent before blaming checkout",
    },
    {
        "id": "first_two_seconds_drop",
        "description": "هبوط كبير في أول ثانيتين",
        "evidence": "Video start strong reach but very low early retention; downstream weak.",
        "acceptable_actions": ["TEST_NEW_HOOK", "SHORTEN_VIDEO", "TEST_NEW_CREATIVE"],
        "principle": "weak hook should produce a concrete creative treatment",
    },
    {
        "id": "good_watch_low_ctr",
        "description": "Watch Time جيد وCTR ضعيف",
        "evidence": "Completion/watch time healthy, clicks below baseline.",
        "acceptable_actions": ["CHANGE_VALUE_PROPOSITION", "ADD_STRONGER_CTA", "SHOW_PRODUCT_EARLIER", "SHOW_PRICE_OR_OFFER", "TEST_NEW_CREATIVE"],
        "principle": "entertaining video can fail to sell",
    },
    {
        "id": "good_ctr_low_atc",
        "description": "CTR جيد وATC ضعيف",
        "evidence": "Clicks healthy, product-page visits healthy, ATC collapses.",
        "must_not_actions": ["PAUSE_AD"],
        "acceptable_root_causes": ["LANDING_PAGE", "PRODUCT", "OFFER"],
        "principle": "investigate landing/product mismatch before traffic punishment",
    },
    {
        "id": "high_atc_low_purchase",
        "description": "ATC مرتفع وPurchase ضعيف",
        "evidence": "Strong click and ATC intent, purchases weak, abandoned carts rising.",
        "must_not_actions": ["PAUSE_CAMPAIGN"],
        "acceptable_root_causes": ["CHECKOUT", "PAYMENT", "SHIPPING", "WEBSITE"],
        "principle": "downstream friction outranks traffic blame",
    },
    {
        "id": "high_checkout_purchase_collapse",
        "description": "Checkout مرتفع وPurchase انهار",
        "evidence": "Initiate checkout normal/high; purchase conversion sharply lower.",
        "acceptable_actions": ["REVIEW_PAYMENT", "REVIEW_CHECKOUT", "REVIEW_SHIPPING", "INVESTIGATE_WEBSITE"],
        "principle": "purchase loss after checkout requires downstream investigation",
    },
    {
        "id": "abandoned_carts_shipping_friction",
        "description": "السلات المتروكة مرتفعة مع إشارة تكلفة شحن",
        "evidence": "High ATC/checkout; store cart abandonment high; shipping cost context elevated.",
        "acceptable_actions": ["REVIEW_SHIPPING_COST", "INVESTIGATE_ABANDONED_CARTS"],
        "must_not_actions": ["PAUSE_CAMPAIGN"],
        "principle": "shipping friction is a store diagnosis not fake campaign attribution",
    },
    {
        "id": "payment_issue_multiple_campaigns",
        "description": "مشكلة دفع تؤثر على عدة حملات",
        "evidence": "Multiple campaigns retain CTR/ATC but purchase drops together; payment corroboration exists.",
        "acceptable_root_causes": ["PAYMENT", "CHECKOUT", "WEBSITE"],
        "principle": "shared downstream failure should not trigger mass traffic pauses",
    },
    {
        "id": "meta_snap_conversion_drop_same_time",
        "description": "Conversion انهار على Meta وSnap بنفس الوقت",
        "evidence": "Meta and Snapchat traffic/ATC stable while store purchases decline simultaneously.",
        "acceptable_root_causes": ["WEBSITE", "CHECKOUT", "PAYMENT", "TRACKING"],
        "principle": "cross-platform corroboration challenges ad-specific explanations",
    },
    {
        "id": "creative_fatigue",
        "description": "Creative fatigue",
        "evidence": "Frequency rising, CTR/retention deteriorating vs own baseline, product funnel healthy.",
        "acceptable_actions": ["REFRESH_CREATIVE", "TEST_NEW_CREATIVE", "TEST_NEW_HOOK"],
        "principle": "fatigue requires creative strategy rather than automatic campaign pause",
    },
    {
        "id": "campaign_learning",
        "description": "Campaign جديدة في Learning",
        "evidence": "Recent creation/edit, learning/delivery status active, limited spend/conversions.",
        "must_not_actions": ["PAUSE_CAMPAIGN"],
        "acceptable_root_causes": ["INSUFFICIENT_DATA", "NORMAL_VARIANCE", "UNKNOWN"],
        "principle": "learning and limited sample are counterfactual evidence",
    },
    {
        "id": "insufficient_data",
        "description": "Campaign بلا بيانات كافية",
        "evidence": "Partial day, low spend, low impressions and conversions.",
        "acceptable_actions": ["NO_ACTION_INSUFFICIENT_DATA", "MONITOR"],
        "principle": "weak sample must not become a strong write recommendation",
    },
    {
        "id": "true_campaign_failure",
        "description": "حملة خاسرة فعلًا ولا يوجد تفسير آخر",
        "evidence": "Persistent weak traffic quality, page/product/checkout healthy, enough sample, history confirms degradation.",
        "acceptable_actions": ["PAUSE_CAMPAIGN", "DECREASE_BUDGET", "REVIEW_AUDIENCE", "TEST_NEW_CREATIVE"],
        "principle": "campaign action is valid only after alternatives are investigated",
    },
    {
        "id": "true_scale_opportunity",
        "description": "حملة ممتازة تستحق Scale",
        "evidence": "Profitable campaign, stable conversion, healthy product/page, sufficient stock/capacity.",
        "acceptable_actions": ["INCREASE_BUDGET", "CONTINUE"],
        "principle": "scale requires commercial and operational capacity evidence",
    },
    {
        "id": "high_watch_video_does_not_sell",
        "description": "Watch Time عالٍ لكن الفيديو لا يبيع",
        "evidence": "High completion/watch time, weak CTR or shopping intent.",
        "acceptable_root_causes": ["CREATIVE", "OFFER"],
        "principle": "attention is not purchase success",
    },
    {
        "id": "average_watch_profitable_sales",
        "description": "Watch Time متوسط لكن المبيعات والربحية ممتازة",
        "evidence": "Video attention average, CTR/CVR/profit excellent.",
        "must_not_actions": ["PAUSE_AD", "PAUSE_CAMPAIGN"],
        "acceptable_actions": ["CONTINUE", "INCREASE_BUDGET", "MONITOR"],
        "principle": "commercial outcome outranks vanity attention metrics",
    },
    {
        "id": "product_url_404_spending",
        "description": "Product URL = 404 والإعلان يصرف",
        "evidence": "Verified product destination returns HTTP 404 while campaign has spend.",
        "acceptable_actions": ["FIX_DESTINATION_URL", "PAUSE_AD", "PAUSE_CAMPAIGN"],
        "acceptable_root_causes": ["PRODUCT_URL", "LANDING_PAGE"],
        "principle": "diagnose broken destination explicitly",
    },
    {
        "id": "product_hidden_spending",
        "description": "Product Hidden والإعلان يعمل",
        "evidence": "Verified linked product is hidden/inactive while advertising spend continues.",
        "acceptable_actions": ["RESTORE_PRODUCT_VISIBILITY", "PAUSE_AD", "PAUSE_CAMPAIGN"],
        "acceptable_root_causes": ["PRODUCT_VISIBILITY", "PRODUCT"],
        "principle": "hidden product is critical operational evidence",
    },
    {
        "id": "product_out_of_stock_spending",
        "description": "Product out of stock والإعلان يعمل",
        "evidence": "Linked product quantity zero, not unlimited, campaign spending.",
        "acceptable_actions": ["REVIEW_INVENTORY", "PAUSE_AD", "PAUSE_CAMPAIGN"],
        "acceptable_root_causes": ["INVENTORY", "PRODUCT"],
        "principle": "protect spend when product cannot be purchased",
    },
    {
        "id": "low_stock_scale_candidate",
        "description": "Stock منخفض والحملة تستحق Scale",
        "evidence": "Campaign commercially strong but inventory estimated under one day.",
        "must_not_executable_actions": ["INCREASE_BUDGET"],
        "acceptable_actions": ["REVIEW_INVENTORY", "CONTINUE", "INCREASE_BUDGET"],
        "principle": "recommendation may discuss scale but write must be blocked by capacity",
    },
    {
        "id": "promoted_variant_out_of_stock",
        "description": "اللون أو المقاس المعلن عنه نفد فقط",
        "evidence": "Product active with stock overall; verified promoted variant quantity zero.",
        "acceptable_root_causes": ["INVENTORY", "PRODUCT"],
        "acceptable_actions": ["REVIEW_INVENTORY", "REVIEW_PRODUCT", "PAUSE_AD"],
        "principle": "variant availability is distinct from total product availability",
    },
    {
        "id": "ad_old_price_product_new_price",
        "description": "السعر تغير لكن الإعلان يعرض السعر القديم",
        "evidence": "Ad message price differs from current product page price.",
        "acceptable_root_causes": ["OFFER", "LANDING_PAGE", "PRODUCT"],
        "acceptable_actions": ["REVIEW_OFFER", "REVIEW_PRODUCT_PAGE", "REFRESH_CREATIVE"],
        "principle": "ad-page mismatch should be explicit",
    },
    {
        "id": "expired_discount_in_ad",
        "description": "الخصم انتهى والإعلان ما زال يعرضه",
        "evidence": "Ad claims discount that current product offer no longer exposes.",
        "acceptable_actions": ["REVIEW_OFFER", "REFRESH_CREATIVE"],
        "principle": "expired offer mismatch is not generic low ROAS",
    },
    {
        "id": "add_to_cart_button_broken",
        "description": "Add To Cart button لا يعمل",
        "evidence": "Page reachable/product in stock but synthetic page evidence cannot expose usable ATC control and ATC collapses.",
        "acceptable_root_causes": ["LANDING_PAGE", "WEBSITE", "ADD_TO_CART"],
        "acceptable_actions": ["REVIEW_PRODUCT_PAGE", "INVESTIGATE_WEBSITE"],
        "principle": "site functionality must be investigated before traffic action",
    },
    {
        "id": "weak_hero_good_traffic",
        "description": "Hero Image ضعيفة مع Traffic ممتاز",
        "evidence": "CTR good; product page ATC weak; visual evidence shows unclear hero presentation.",
        "acceptable_actions": ["CHANGE_HERO_IMAGE", "REVIEW_PRODUCT_PAGE"],
        "principle": "specific product-page creative treatment is preferable to vague optimization",
    },
    {
        "id": "description_missing_objections",
        "description": "الوصف ناقص ويترك اعتراضات العميل بدون جواب",
        "evidence": "Product description lacks sizing/material/contents/fulfillment clarity; traffic quality healthy.",
        "acceptable_actions": ["CHANGE_PRODUCT_DESCRIPTION", "REVIEW_PRODUCT_PAGE"],
        "principle": "propose concrete product copy remedy",
    },
    {
        "id": "price_high_value_strong",
        "description": "السعر أعلى من السوق لكن Value proposition قوية",
        "evidence": "Comparable market price lower, but product differentiation/reviews/conversion/profit are strong.",
        "must_not_actions": ["PAUSE_CAMPAIGN"],
        "acceptable_actions": ["CONTINUE", "MONITOR", "REVIEW_PRICE"],
        "principle": "competitor cheaper does not force price reduction",
    },
    {
        "id": "price_high_value_unclear",
        "description": "السعر أعلى من السوق بدون Value واضحة",
        "evidence": "Price premium with weak ATC and unclear differentiation.",
        "acceptable_root_causes": ["OFFER", "PRODUCT", "LANDING_PAGE"],
        "acceptable_actions": ["REVIEW_PRICE", "CHANGE_VALUE_PROPOSITION", "REVIEW_PRODUCT_PAGE"],
        "principle": "distinguish price level from value explanation",
    },
    {
        "id": "price_change_then_atc_drop",
        "description": "تغيير سعر المنتج تسبب في هبوط ATC",
        "evidence": "Price changed at known timestamp; CTR stable; ATC drops immediately after change.",
        "acceptable_root_causes": ["OFFER", "PRODUCT"],
        "acceptable_actions": ["REVIEW_PRICE", "REVIEW_OFFER"],
        "principle": "product change chronology should challenge campaign blame",
    },
    {
        "id": "employee_hid_product_while_ads_run",
        "description": "الموظف أخفى المنتج أثناء تشغيل الإعلان",
        "evidence": "Visibility status changed to hidden during active advertising spend.",
        "acceptable_actions": ["RESTORE_PRODUCT_VISIBILITY", "PAUSE_AD", "PAUSE_CAMPAIGN"],
        "acceptable_root_causes": ["PRODUCT_VISIBILITY"],
        "principle": "visibility change is a critical operational root cause",
    },
    {
        "id": "api_product_ok_public_page_broken",
        "description": "المنتج يعمل من API لكن الصفحة الفعلية للعميل لا تعمل",
        "evidence": "Product API active/in-stock; public canonical page probe fails or is unavailable.",
        "acceptable_actions": ["FIX_DESTINATION_URL", "INVESTIGATE_WEBSITE", "REVIEW_PRODUCT_PAGE"],
        "acceptable_root_causes": ["PRODUCT_URL", "WEBSITE", "LANDING_PAGE"],
        "principle": "customer-visible page truth can override optimistic catalog status",
    },
]

assert len(SCENARIOS) == 33
