import test from "node:test";
import assert from "node:assert/strict";
import {MODEL_VERSION, PREFIX, PERMISSION_KEYS, CARDS, TABS, ROUTE_CONTRACT, moneyText, countText, canSee, canOpenTab, viewState, detailFor, scopedRows} from "./advertisingAccountsDraftContract.js";
const row = {owner_id: "owner-a", linked_account_ref: "link-1", ad_provider: "snapchat", external_account_id: "external-1"};
const model = (accounts = [row]) => ({version: MODEL_VERSION, owner_id: "owner-a", status: "ready", accounts});
test("nine summary cards and eight tabs", () => {assert.equal(CARDS.length, 9); assert.equal(TABS.length, 8);});
test("no route activation", () => {assert.equal(ROUTE_CONTRACT.registered, false); assert.match(ROUTE_CONTRACT.shell, /workspace=financial&page=advertising-accounts/);});
test("unknown financial values never become zero", () => {for (const value of [null, undefined, 0, NaN, "", "NaN", "١٢٣"]) assert.equal(moneyText(value), "غير متاح");});
test("known zero and negative difference keep English digits", () => {assert.equal(moneyText("0"), "0.00"); assert.equal(moneyText("-50"), "-50.00");});
test("large exact amounts avoid binary float", () => assert.equal(moneyText("100000000000000001.12"), "100,000,000,000,000,001.12"));
test("unsafe counts unavailable", () => {assert.equal(countText(0), "0"); assert.equal(countText(-1), "غير متاح"); assert.equal(countText(Number.MAX_SAFE_INTEGER + 1), "غير متاح");});
test("all grants fail closed and no posting grant", () => {for (const permission of PERMISSION_KEYS) assert.equal(canSee(PERMISSION_KEYS, permission), permission !== PREFIX + "journals.post"); assert.equal(canSee([], PREFIX + "view"), false); assert.equal(canSee(PREFIX + "view", PREFIX + "view"), false);});
test("missing adapter is not empty live registry", () => {const result = viewState("owner-a", null); assert.equal(result.status, "dependency_blocked"); assert.equal(result.summary, null);});
test("only provided linked accounts", () => assert.deepEqual(viewState("owner-a", model()).accounts, [row]));
test("no invented provider or free incomplete identity", () => {assert.equal(viewState("owner-a", model([{...row, ad_provider: "free"}])).code, "ACCOUNT_NOT_LINKED"); assert.equal(viewState("owner-a", model([{...row, linked_account_ref: null}])).code, "ACCOUNT_NOT_LINKED");});
test("duplicate identity blocked even with different link", () => assert.equal(viewState("owner-a", model([row, {...row, linked_account_ref: "link-2"}])).code, "DUPLICATE_SOURCE"));
test("duplicate link blocked even with different identity", () => assert.equal(viewState("owner-a", model([row, {...row, external_account_id: "external-2"}])).code, "DUPLICATE_SOURCE"));
test("owner boundaries checked on envelope and rows", () => {assert.equal(viewState("owner-b", model()).code, "OWNER_SCOPE_MISMATCH"); assert.equal(viewState("owner-a", model([{...row, owner_id: "owner-b"}])).code, "OWNER_SCOPE_MISMATCH");});
test("detail owner and account must match", () => {assert.equal(detailFor({details: {"link-1": {...row, owner_id: "owner-b"}}}, "owner-a", "link-1"), null); assert.deepEqual(detailFor({details: {"link-1": row}}, "owner-a", "link-1"), row);});
test("child rows fail closed on mixed owner or missing data", () => {assert.equal(scopedRows({...row, daily: [{...row, owner_id: "owner-b"}]}, "daily"), null); assert.deepEqual(scopedRows({...row, daily: []}, "daily"), []); assert.equal(scopedRows(row, "daily"), null);});
test("debt reviewer can inspect invoices without invoice-management grant", () => {assert.equal(canOpenTab([PREFIX + "debts.review"], TABS.find(t => t.id === "invoices")), true); assert.equal(canSee([PREFIX + "debts.review"], PREFIX + "invoices.manage"), false);});
test("source error stays unavailable rather than zero", () => {const result = viewState("owner-a", {...model(), status: "error"}); assert.equal(result.status, "error"); assert.equal(result.summary, null);});
