/*
 * Mezan OS product preview data.
 *
 * This file intentionally follows Salla's Product Details By SKU response
 * fields (product fields, options/values, and variant SKUs). The UI adapter
 * calls the variant collection `variants` (Salla exposes it as `skus`).
 * It remains fully isolated from legacy products and product_costs domains.
 * Nothing in this fixture is accounting data and nothing is sent to Salla.
 */

export const MEZAN_PRODUCT_PREVIEW_META = {
    mode: "virtual",
    label: "بيانات افتراضية — لا تؤثر على سلة أو المحاسبة",
    salla_scope: "products.read",
    reference_sku: "AMS10026",
};

const money = (amount) => ({ amount, currency: "SAR" });

export const MEZAN_PRODUCT_PREVIEW_FIXTURES = [
    {
        id: "preview-salla-ams10026",
        salla_id: null,
        sku: "AMS10026",
        name: "AMS10026 — نموذج مرجعي لبنية سلة",
        description: "هذا نموذج افتراضي لبناء واجهة التكاليف. الاسم والصورة والخيارات الفعلية ستأتي من سلة بعد اعتماد صلاحية قراءة المنتجات.",
        type: "product",
        status: "awaiting_scope",
        is_available: null,
        source: "virtual_salla_schema",
        source_note: "القيم التالية توضح شكل البيانات فقط وليست نسخة فعلية من المنتج في سلة.",
        salla_snapshot_complete: false,
        thumbnail: "",
        main_image: "",
        price: money(149),
        taxed_price: money(171.35),
        pre_tax_price: money(149),
        tax: money(22.35),
        sale_price: money(0),
        cost_price: money(0),
        quantity: 18,
        unlimited_quantity: false,
        notify_quantity: 5,
        require_shipping: true,
        weight: 0.2,
        weight_type: "kg",
        categories: [{ id: "preview-category-jewelry", name: "مجوهرات — تجريبي" }],
        options: [
            {
                id: "preview-option-ams10026-1",
                name: "الخيار الأول — تجريبي",
                type: "radio",
                display_type: "text",
                required: true,
                values: [
                    { id: "preview-value-ams10026-a", name: "قيمة A", price: money(0), is_default: true, is_out_of_stock: false },
                    { id: "preview-value-ams10026-b", name: "قيمة B", price: money(10), is_default: false, is_out_of_stock: false },
                ],
            },
            {
                id: "preview-option-ams10026-2",
                name: "الخيار الثاني — تجريبي",
                type: "radio",
                display_type: "text",
                required: true,
                values: [
                    { id: "preview-value-ams10026-c", name: "قيمة 1", price: money(0), is_default: true, is_out_of_stock: false },
                    { id: "preview-value-ams10026-d", name: "قيمة 2", price: money(0), is_default: false, is_out_of_stock: false },
                ],
            },
        ],
        variants: [
            {
                id: "preview-variant-ams10026-a1",
                sku: "AMS10026-A-1",
                price: money(149),
                sale_price: money(0),
                stock_quantity: 8,
                related_option_values: ["preview-value-ams10026-a", "preview-value-ams10026-c"],
                cost: { supplier: 42, labor: 8, packaging: 4.5, extra: 0 },
                cost_status: "ready",
            },
            {
                id: "preview-variant-ams10026-a2",
                sku: "AMS10026-A-2",
                price: money(149),
                sale_price: money(0),
                stock_quantity: 6,
                related_option_values: ["preview-value-ams10026-a", "preview-value-ams10026-d"],
                cost: { supplier: 42, labor: 9, packaging: 4.5, extra: 2 },
                cost_status: "ready",
            },
            {
                id: "preview-variant-ams10026-b1",
                sku: "AMS10026-B-1",
                price: money(159),
                sale_price: money(0),
                stock_quantity: 4,
                related_option_values: ["preview-value-ams10026-b", "preview-value-ams10026-c"],
                cost: { supplier: "", labor: "", packaging: "", extra: "" },
                cost_status: "needs_cost",
            },
        ],
    },
    {
        id: "preview-simple-product",
        salla_id: "PREVIEW-10002",
        sku: "DEMO-SIMPLE-001",
        name: "منتج بسيط بدون خيارات",
        description: "حالة اختبار لمنتج سلة بسيط له SKU واحد وتكلفة واحدة.",
        type: "product",
        status: "sale",
        is_available: true,
        source: "virtual",
        source_note: "منتج افتراضي للاختبار فقط.",
        salla_snapshot_complete: true,
        thumbnail: "",
        main_image: "",
        price: money(89),
        taxed_price: money(102.35),
        pre_tax_price: money(89),
        tax: money(13.35),
        sale_price: money(0),
        cost_price: money(0),
        quantity: 25,
        unlimited_quantity: false,
        notify_quantity: 5,
        require_shipping: true,
        weight: 0.1,
        weight_type: "kg",
        categories: [{ id: "preview-category-simple", name: "منتجات بسيطة — تجريبي" }],
        options: [],
        variants: [
            {
                id: "preview-variant-simple",
                sku: "DEMO-SIMPLE-001",
                price: money(89),
                sale_price: money(0),
                stock_quantity: 25,
                related_option_values: [],
                cost: { supplier: 31, labor: 4, packaging: 3.5, extra: 1 },
                cost_status: "ready",
            },
        ],
    },
    {
        id: "preview-custom-product",
        salla_id: "PREVIEW-10003",
        sku: "DEMO-CUSTOM-001",
        name: "منتج مخصص بخيارات عميل",
        description: "حالة اختبار لمنتج يجمع متغيرات مخزنية مع حقل تخصيص لا ينشئ متغيرًا مستقلًا.",
        type: "product",
        status: "sale",
        is_available: true,
        source: "virtual",
        source_note: "منتج افتراضي للاختبار فقط.",
        salla_snapshot_complete: true,
        thumbnail: "",
        main_image: "",
        price: money(179),
        taxed_price: money(205.85),
        pre_tax_price: money(179),
        tax: money(26.85),
        sale_price: money(0),
        cost_price: money(0),
        quantity: 14,
        unlimited_quantity: false,
        notify_quantity: 3,
        require_shipping: true,
        weight: 0.25,
        weight_type: "kg",
        categories: [{ id: "preview-category-custom", name: "منتجات مخصصة — تجريبي" }],
        options: [
            {
                id: "preview-option-custom-size",
                name: "المقاس — تجريبي",
                type: "radio",
                display_type: "text",
                required: true,
                values: [
                    { id: "preview-value-custom-small", name: "صغير", price: money(0), is_default: true, is_out_of_stock: false },
                    { id: "preview-value-custom-large", name: "كبير", price: money(15), is_default: false, is_out_of_stock: false },
                ],
            },
            {
                id: "preview-option-custom-text",
                name: "النص المطلوب — تجريبي",
                type: "text",
                display_type: "text",
                required: true,
                values: [],
                creates_variant: false,
            },
        ],
        variants: [
            {
                id: "preview-variant-custom-small",
                sku: "DEMO-CUSTOM-S",
                price: money(179),
                sale_price: money(0),
                stock_quantity: 9,
                related_option_values: ["preview-value-custom-small"],
                cost: { supplier: 52, labor: 14, packaging: 6, extra: 3 },
                cost_status: "ready",
            },
            {
                id: "preview-variant-custom-large",
                sku: "DEMO-CUSTOM-L",
                price: money(194),
                sale_price: money(0),
                stock_quantity: 5,
                related_option_values: ["preview-value-custom-large"],
                cost: { supplier: "", labor: "", packaging: "", extra: "" },
                cost_status: "needs_cost",
            },
        ],
    },
];
