import React from "react";
import OpeningCourierEditor, { OpeningField } from "./OpeningCourierEditor";
import OpeningEntityEditor from "./OpeningEntityEditor";
import OpeningInventoryEditor from "./OpeningInventoryEditor";
import OpeningTermsEditor from "./OpeningTermsEditor";
import { ONBOARDING_STAGES, sectionIndicators, sectionPresentation } from "./onboardingStages";

const ENTITY_KEYS = { banks: "financial_accounts", providers: "payment_providers", employees: "employees", suppliers: "suppliers", external_persons: "external_persons", drivers: "store_drivers", advertising: "ad_accounts" };
const buttonClass = "rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-bold disabled:opacity-40";

// Controlled presentation only. These UI keys are not a proposed Track A wire contract.
// No route, autosave, session endpoint or persistence fallback is installed here.
export default function OnboardingWizardView({ value = {}, onChange, activeStage = "cutover", onStageChange, context = {}, onSaveSection, onCreateExternalPerson, onEntityCreated, busy = false, saveMessage = "", errors = [], financialBinding = false, readOnly = false, setupContent = null, richShippingContent = null, richShippingSupported = false }) {
    const stage = ONBOARDING_STAGES.find(s => s.id === activeStage) || ONBOARDING_STAGES[0];
    const index = ONBOARDING_STAGES.findIndex(s => s.id === stage.id);
    const sections = value.sections || {};
    const section = sections[stage.id] || {};
    // Fees save with the providers section. This status describes that shared
    // section; selected policy validity remains the server preview's decision.
    const usesProviderSection = id => financialBinding && context.ssotSetupSupported && id === "payment_fees";
    const displaySection = id => sections[usesProviderSection(id) ? "providers" : id];
    const displayIndicators = id => `${usesProviderSection(id) ? "قسم المزوّدين: " : ""}${sectionIndicators(displaySection(id), id).join(" · ")}`;
    const entities = context.entities || {};
    const patch = changes => onChange({ ...value, sections: { ...sections, [stage.id]: { ...section, ...changes } } });
    const updateRows = rows => patch({ rows, status: "incomplete", explicit_zero: false });
    const couriers = value.couriers || {};
    const completed = ONBOARDING_STAGES.slice(0, 14).filter(s => ["complete", "not_applicable"].includes(sectionPresentation(sections[s.id], s.id).status)).length;
    const save = () => onSaveSection?.(stage.id, section);
    return <main dir="rtl" lang="ar" className="mx-auto max-w-7xl space-y-6 p-4 text-slate-900 md:p-8" data-testid="onboarding-wizard">
        <header className="rounded-2xl bg-emerald-950 p-6 text-white"><p className="text-sm text-emerald-200">ميزان 2 · تأسيس الدفتر</p><h1 className="mt-2 text-2xl font-black">أرصدة موثقة لبداية واضحة</h1><p className="mt-3 text-sm leading-7">أكمل كل جهة بأرقامها وأدلتها عند لحظة القطع. الحقول الفارغة ليست صفرًا.</p><p className="mt-3 text-sm">P02 — LOCKED · الترحيل والتفعيل غير متاحين في هذا المسار</p></header>
        <div className="grid gap-6 lg:grid-cols-[280px_minmax(0,1fr)]">
            <aside className="min-w-0 rounded-2xl border bg-white p-4"><p className="font-bold" role="status">{financialBinding ? "16 مرحلة · التقدم المالي موضح في الأقسام السبعة" : `أقسام الإدخال: ${completed} / 14`}</p>{!financialBinding && <progress className="my-3 w-full" max="14" value={completed} aria-label="تقدم أقسام الإدخال" />}<nav aria-label="مراحل التأسيس" className="flex gap-2 overflow-x-auto lg:block lg:space-y-1">{ONBOARDING_STAGES.map((s, i) => <button type="button" key={s.id} disabled={busy} aria-current={s.id === stage.id ? "step" : undefined} onClick={() => onStageChange(s.id)} className={`min-w-48 rounded-xl p-3 text-right text-sm lg:w-full ${s.id === stage.id ? "bg-emerald-100 font-bold text-emerald-950" : "hover:bg-slate-50"}`}><span className="me-2 text-slate-500">{String(i + 1).padStart(2, "0")}</span>{s.label}<span className="mt-1 block text-xs text-slate-500">{financialBinding && (s.id === "courier_contracts" || s.id === "payment_fees" && !context.ssotSetupSupported) ? (s.id === "courier_contracts" && richShippingSupported ? "عقود محفوظة ومراجعة مستقلة" : "مسودة محلية") : i < 14 ? displayIndicators(s.id) : i === 14 ? "ملخص الأقسام" : "مقفل"}</span></button>)}</nav></aside>
            <section className="min-w-0 space-y-5 rounded-2xl border bg-white p-5 md:p-7"><div><p className="text-sm font-bold text-emerald-800">المرحلة {index + 1} من 16</p><h2 className="mt-2 text-xl font-black">{stage.label}</h2></div>
                {!onSaveSection && <p role="status" className="rounded-xl bg-amber-50 p-3 text-sm">محرر تحضيري: الحفظ واستعادة الجلسة غير موصولين في هذا العرض المستقل. التعديلات غير محفوظة على الخادم.</p>}
                {stage.id === "courier_contracts" && richShippingContent}
                <fieldset disabled={readOnly || busy} className="min-w-0 space-y-4">
                {stage.id === "cutover" && <div className="space-y-4"><OpeningField label="لحظة القطع — Asia/Riyadh" type="datetime-local" value={section.cutover_at} onChange={v => patch({ cutover_at: v, status: "incomplete" })} /><p className="text-sm">هدف القطع: 2026-10-01 00:00 Asia/Riyadh. يجب تأكيد الحقل صراحة.</p><OpeningField label="مرجع دليل القطع — مطلوب" value={section.evidence_ref} onChange={v => patch({ evidence_ref: v, status: "incomplete" })} /></div>}
                {ENTITY_KEYS[stage.id] && <OpeningEntityEditor key={stage.id} domain={stage.id} value={section.rows || []} onChange={updateRows} entities={entities[ENTITY_KEYS[stage.id]] || []} banks={entities.banks || []} financialAccounts={context.financial_accounts || []} createExternalPerson={onCreateExternalPerson} onEntityCreated={onEntityCreated} />}
                {stage.id === "courier_contracts" && !richShippingContent && <OpeningCourierEditor value={couriers} onChange={next => onChange({ ...value, couriers: next, sections: { ...sections, courier_contracts: { ...sections.courier_contracts, status: "incomplete" }, courier_balances: { ...sections.courier_balances, status: "incomplete" } } })} couriers={entities.couriers || []} banks={entities.banks || []} onSave={onSaveSection ? (id, draft) => onSaveSection("courier_contracts", { courier_id: id, draft }) : undefined} busy={busy} />}
                {stage.id === "courier_balances" && <><p>الأرصدة مستقلة لكل شركة، وتُحرر مع مسودة الشركة في المرحلة 7.</p><div className="overflow-x-auto"><table className="w-full text-right text-sm"><thead><tr><th className="p-3">الشركة</th><th>COD لنا</th><th>مستحق للشركة</th><th>الدليل</th></tr></thead><tbody>{Object.entries(couriers).map(([id, draft]) => <tr key={id} className="border-t"><td className="p-3">{entities.couriers?.find(c => c.id === id)?.name || id}</td><td>{draft.opening_cod_receivable === "" ? "ناقص" : draft.opening_cod_receivable}</td><td>{draft.opening_payable === "" ? "ناقص" : draft.opening_payable}</td><td>{draft.evidence_ref || "دليل ناقص"}</td></tr>)}</tbody></table></div><button type="button" className={buttonClass} onClick={() => onStageChange("courier_contracts")}>تحرير شركة وأرصدتها</button></>}
                {stage.id === "inventory" && <OpeningInventoryEditor value={section.rows || []} onChange={updateRows} context={context.inventory || {}} />}
                {["payment_fees", "prepaid", "obligations"].includes(stage.id) && (setupContent || <OpeningTermsEditor key={stage.id} domain={stage.id} value={section.rows || []} onChange={updateRows} classifications={context.classifications?.[stage.id] || []} providers={entities.payment_providers || []} feeConfigurationSupported={context.feeConfigurationSupported === true} />)}
                {stage.id === "review" && <><p>حالة كل قسم وأدلته. هذا العرض ليس معاينة قيد من الخادم ولا إثبات جاهزية للترحيل.</p><div className="overflow-x-auto"><table className="w-full text-right text-sm"><thead><tr><th className="p-3">القسم</th><th>الحالة</th><th>الدليل</th></tr></thead><tbody>{ONBOARDING_STAGES.slice(0, 14).map(s => <tr className="border-t" key={s.id}><td className="p-3"><button type="button" className="text-emerald-800 underline" onClick={() => onStageChange(s.id)}>{s.label}</button></td><td>{financialBinding && (s.id === "courier_contracts" || s.id === "payment_fees" && !context.ssotSetupSupported) ? (s.id === "courier_contracts" && richShippingSupported ? "عقود محفوظة ومراجعة مستقلة" : "مسودة محلية") : displayIndicators(s.id)}</td><td>{financialBinding && (s.id === "courier_contracts" || s.id === "payment_fees" && !context.ssotSetupSupported) ? "خارج الحفظ المالي" : displaySection(s.id)?.evidence_ref || "دليل ناقص"}</td></tr>)}</tbody></table></div></>}
                {stage.id === "approval" && <div role="status" className="space-y-3 rounded-xl border border-amber-200 bg-amber-50 p-5"><h3 className="font-black">الاعتماد النهائي مقفل</h3><p>لا يوجد إجراء ترحيل أو تفعيل في هذه الواجهة. يلزم عقد النواة، ومعاينة ومراجعة معتمدتان، وتفويض مستقل لمسار القطع.</p><p>P02 وG47 غير مفعّلين بواسطة هذا المعالج.</p></div>}
                {index < 14 && !financialBinding && <div className="space-y-3 border-t pt-5"><OpeningField label="مرجع دليل القسم" value={section.evidence_ref} onChange={v => patch({ evidence_ref: v, status: "incomplete" })} />{!["cutover", "courier_contracts", "payment_fees"].includes(stage.id) && <label className="block"><input type="checkbox" checked={section.explicit_zero === true} onChange={e => patch({ explicit_zero: e.target.checked, status: "incomplete" })} /> أؤكد أن القسم صفر صريح وفق الدليل</label>}{stage.id !== "cutover" && <label className="block"><input type="checkbox" checked={section.status === "not_applicable"} onChange={e => patch({ status: e.target.checked ? "not_applicable" : "incomplete" })} /> لا ينطبق هذا القسم</label>}{section.status === "not_applicable" && <OpeningField label="سبب عدم الانطباق" value={section.not_applicable_reason} onChange={v => patch({ not_applicable_reason: v })} />}<button type="button" className="rounded-xl bg-emerald-800 px-5 py-3 font-bold text-white disabled:opacity-40" disabled={busy || !onSaveSection} onClick={save}>حفظ القسم</button></div>}
                </fieldset>
                {errors.length > 0 && <ul role="alert" className="rounded-lg bg-rose-50 p-4 text-rose-900">{errors.map((e, i) => <li key={i}>{typeof e === "string" ? e : e.message}</li>)}</ul>}
                {saveMessage && <p role="status">{saveMessage}</p>}
                <div className="flex justify-between border-t pt-4"><button type="button" className={buttonClass} disabled={index === 0 || busy} onClick={() => onStageChange(ONBOARDING_STAGES[index - 1].id)}>السابق</button><button type="button" className={buttonClass} disabled={index === 15 || busy} onClick={() => onStageChange(ONBOARDING_STAGES[index + 1].id)}>التالي</button></div>
            </section>
        </div>
    </main>;
}
